services:
  - type: web
    name: datalens-ai-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    rootDir: backend
    
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: GEMINI_MODEL
        value: gemini-flash-latest
